version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"    # RabbitMQ protocol port
      - "15672:15672"  # RabbitMQ management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network

  celery:
    build:
      context: .
      dockerfile: ./path/online_store_kian/Dockerfile
    command: celery -A online_store_kian worker --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
