

services:
  web:
    build: .
    command: [ "./entrypoint.web.sh", "gunicorn", "src.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120" ]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
  celery:
    build: .
    command: [ "./entrypoint.celery.sh" ]
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media:/app/media
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media:
